config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/signout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    
    member do
      post :vote
    end

=begin
    #GET /posts/archives
    collection do
      get :archives
    end      
=end
   
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end

  end
  
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :show, :edit, :update] 
 
  #get 'photos/poll', to: 'photos#poll'
end

=begin
How to route the votes

1) If voting on alot of stuff do this
POST /votes => 'VotesController#create'
- the form will need to pass 2 pieces of information
resources :votes, only: [:create]

2)
POST /post/3/vote => 'PostsController#vote'
POST /comments/4/vote => 'CommentsController#vote'

=end 

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post #do not have to define foreign key because the assumptions are correct. Class is Post
  has_many :votes, as: :voteable
  
  validates :body, presence: true
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 # 2. redirect based on some condition
before_action :require_user
  
####################### CREATE A COMMENT #######################
  def create
    #binding.pry
    #@post = Post.find(params[:post_id])
    @post = Post.find_by(slug: params[:post_id])

    @comment = @post.comments.build(comment_params) #mass assign via strong parameters
             # Comment.new(params.require(:comment).permit(:body)) #stop assignment, mass assigning body
             # @post.comments.new(params.require(:comment).permit(:body))
    #@comment = Comment.new(params.require(:comment).permit(:body))
    #@comment.post = @post
    @comment.creator = current_user         
    if @comment.save
      flash[:notice] = "Your comment was added"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

####################### VOTE ACTION #######################

  def vote
    #binding.pry
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])
    #@vote = Vote.create(voteable_type: "Comment", voteable_id: params[:id]) 
    respond_to do |format|
      format.html do
        if !@vote.errors.any? #instead of @votes.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote on \"#{@comment.body}\" once."
          #flash[:error] = "You can only vote on <strong>that</strong> once.".html_safe
        end
        redirect_to :back #whatever your referral is, go back to that url
      end
      format.js do
        render :vote
      end
    end

  end

private

####################### PRIVATE COMMENTS CONTROLLER METHODS #######################

  def comment_params
    params.require(:comment).permit(:body)
  end

end

# redirect -> URLs
# render -> template file

app/views/comments/_comment.html.erb
<!-- if show_post doesn't exist use the initialized here-->
<% show_post ||= false %>
<div class="row">
  <div class='span0 well text-center'>
    <% # need to pass two objects below: Post object and a Comment obect) %>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
      <i class='icon-arrow-up'></i>
    <% end %>
    <br/>
    <span id= 'comment_<%= comment.id %>_votes'><%= "#{comment.total_votes} votes"%></span>
    <br/>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
      <i class='icon-arrow-down'></i>
    <% end %>
  </div>
  <div class ='well span8'>
    <em><%= comment.body %></em>
    <% if show_post %>
      on <%= link_to comment.post.title, post_path(comment.post) %>
    <% end %>
    </br>
    <span class='quiet'>comment by </span><%= link_to comment.creator.username, user_path(comment.creator) %>
    <small> at <%= display_datetime(comment.created_at) %></small>
  </div>
</div>

app/views/comments/vote.js.erb
<% if !@vote.errors.any? %>
  $("#comment_<%= @comment.id %>_votes").html("<%= @comment.total_votes %> votes");
<% else %>
  alert('You can only vote on a comment once!')
<% end %>