config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/signout', to: 'sessions#destroy'

  resources :posts, except: [:destroy] do
    
    member do
      post :vote
    end

=begin
    #GET /posts/archives
    collection do
      get :archives
    end      
=end
   
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end

  end
  
  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:create, :show, :edit, :update] 
 
  #get 'photos/poll', to: 'photos#poll'
end

=begin
How to route the votes

1) If voting on alot of stuff do this
POST /votes => 'VotesController#create'
- the form will need to pass 2 pieces of information
resources :votes, only: [:create]

2)
POST /post/3/vote => 'PostsController#vote'
POST /comments/4/vote => 'CommentsController#vote'

=end 

app/models/post.rb
class Post < ActiveRecord::Base
  
  include Voteable
  include Sluggable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  # the code below has been moved into the lib/voteable.rb file
  #has_many :votes, as: :voteable

  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true
  validates :description, presence: true

  # moved the code below to the lib/sluggable.rb file
  # before_save :generate_slug!
  #use before_create if you don't want the slug to be regenerated

  sluggable_column :title
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  # 1. set up instance variable for action
  before_action :set_post, only: [:show, :edit, :update, :vote]

  # 2. redirect based on some condition
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]

####################### DISPLAYING EXISTING POSTS #######################
  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
    #binding pry
  end

  def show
    @comment = Comment.new
    @category = Category.new
    render :show  #this would have happened by default anyways
  end

####################### MAKE A NEW POST #######################

  def new #show the post form
    @post = Post.new
  end

  def create #handle the submission of the new post form   
    @post = Post.new(post_params)
    @post.creator = current_user #TODO change once we have authentication

    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to post_path(@post)
    else # validation error
      render :new
    end
  end

####################### MODIFY AN EXISTING POST #######################

  def edit #display the edit post form /posts/:id/edit
  end

  def update #handle the submission of that edit post form
    
    if @post.update(post_params)
      flash[:notice] = "The post was updated"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

####################### VOTE ACTION #######################

  def vote

    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if !@vote.errors.any? #instead of @votes.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote on \"#{@post.title}\" once."
          #flash[:error] = "You can only vote on <strong>that</strong> once.".html_safe
        end
        redirect_to :back #whatever your referral is, go back to that url
      end
      format.js do
        render :vote
      end
    end
  end

####################### PRIVATE POSTS CONTROLLER METHODS #######################
  private

  def post_params
    
    params.require(:post).permit!

    #if user.admin?
    #  params.require(:post).permit!
    #else
    #  params.require(:post).permit(:title, :url)
    #end
  end

  def set_post
   # @post = Post.find(params[:id])
   @post = Post.find_by(slug: params[:id])
  end

  def post_edit_denied
    flash[:error] = "Sorry, only the creator of the post can edit!"
    redirect_to root_path
  end
  
  def require_creator
    #if logged_in? and (current_user.admin? || (current_user.username == post.creator.username))
    #post_edit_denied if !logged_in? and (current_user != @post.creator)
    post_edit_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
  end

end

app/views/posts/_form.html.erb
<%=render 'shared/errors', obj: @post %>  

<div class='well'>
  <!--Rails model-backed forms-->  
  <%-#-- syntax is <%= form_for OBJ do |f| -%>
  <%= form_for @post do |f| %>
    <div class='control-group'>
      <%= f.label :title, "Title" %>
      <%= f.text_field :title %>
    </div>
    <div class='control-group'> 
      <%= f.label :url, "URL" %>
      <%= f.text_field :url %>
    </div> 
    <div class='control-group'>
    <%= f.label :description, "Description" %>
      <%= f.text_area :description, rows: 5, cols: 100 %>
    </div> 
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
      <%-#checkbox inline is a Twitter Bootstrap thing-%>
    <% end %>
    
    <!--
    <select name='post[category_ids][]', multiple="multiple">
      <option value='1'>News</option>
      <option value='2'>Technology</option>
    </select>
    -->
    <br/><br/>
    <%= f.submit(@post.new_record? ? "Create Post" : "Update Post", class: 'btn btn-primary') %>
  <% end %> 
</div> 

app/views/posts/_post.html.erb
<div class="row">
  <div class='span0 well text-center'>
    <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
      <i class='icon-arrow-up'></i>
    <% end %>
    <br/>
    <span id= 'post_<%= post.slug %>_votes'><%= "#{post.total_votes} votes"%></span>
    <br/>
    <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
      <i class='icon-arrow-down'></i>
    <% end %>
  </div>
    <div class='span8 well'> 
      <%= render post.categories %>
      <h4>
        <%= link_to post.title, post_path(post) %>
        <% if logged_in? and (current_user.admin? || (current_user.username == post.creator.username)) %>
          (<%= link_to 'edit', edit_post_path(post) %>)
        <% end %>
        <br/>
      </h4>

      <p>
        <%= link_to post.url, fix_url(post.url), target: '_blank' %>
        <br/>
        <%= post.description %>
      </p>
      <p>
        <span class='quiet'> posted by </span> <%= link_to post.creator.username, user_path(post.creator) %>
        <small>
          at <%= display_datetime(post.created_at)%>
        </small>
      </p>
      <small>
        <span>
          <%= link_to("#{post.comments.size} comments", post_path(post)) %>
        </span>
      </small>
    </div>
</div>

app/views/posts/edit.html.erb
<h4>Edit this post</h4>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>
<!--no underscore before partial html template-->

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

<%-#% if !@posts.empty? -%>
  <%-#= render @posts -%>
  <!-- This is how to render partial with collection -->
  <%-# render :partial => 'post', :collection => @posts -%>
<%-# end -%>

app/views/posts/new.html.erb
<h4>Create a new Post</h4>
<%= render 'form' %>

<!--
<h5>Pure HTML Form</h5>
<form action='/posts' method='POST'>
  Title: <input type='text'name='title'>
  <br/>
  <input type='submit' class='btn btn-primary'>
</form>

<h4>Rails form helpers</h4>
<#%= form_tag '/posts' do %>
  <#%= label_tag :title, "Input a title" %>
  <#%= text_field_tag :title %>
  <br/>
  <#%= submit_tag "Create Post", class: 'btn btn-primary' %>
<% #end %>
-->

app/views/posts/show.html.erb
<% @post.categories.each do |category| %>
  <%= render category %>
<% end %>
<p/>
<p class='pull-right'>
  <%= link_to 'show all posts', posts_path %>
</p>
<%= render 'shared/content_title', title: @post.title %> 

<% if logged_in? and (current_user.admin? || (current_user.username == @post.creator.username)) %>
  <p class='pull-right'>
    [<%= link_to 'edit this post', edit_post_path(@post) %>]
  </p>
<% end %>

<p>
  <%= link_to @post.url %>
</p>
<p>
  <%= @post.description %>
</p>
<hr/>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%=render 'shared/errors', obj: @comment %>
      <div class ='control-group'>
      <%= f.label :body, 'Leave a comment' %>
      <%= f.text_area :body, rows: 3, class: 'span4' %>
      </div>
      <%= f.submit "Create Comment", class: "btn btn-primary" %>  
  <% end %>
<% end %>

<h5>Comments:</h5>
<% @post.reload.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment, show_post: false %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.slug %>_votes").html("<%= @post.total_votes %> votes");
<% else %>
  alert('You can only vote on a post once')
<% end %>